config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Implementing a static route
  # to access we go to localhost:3000/about
  # make sure we have a controller 'static' with a method "about"
  # name of view folder needs to match 
  # "xyz" where "xyz"_controller
  get 'about', to: 'static#about'


  # this allows route /exercise
  resources :exercises, only: [:index, :new, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

    def index
        @exercises = Exercise.all
    end
    
    def show
        @exercise = Exercise.find(params[:id])
    end

    def new
        @exercise = Exercise.new
    end

    def create
        @exercise = Exercise.create(exercise_params)
        @exercise.save
        redirect_to exercise_path(@exercise)
    end

    def exercise_params
        params.require(:exercise).permit(:description)
    end

end

app/controllers/static_controller.rb
#
class StaticController < ApplicationController

    def about
        render "some_page"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exercises/index.html.erb
<h1> All the Exercises </h1>
<% @exercises.each do |exercise| %>
    <div><%= link_to exercise.description, exercise_path(exercise)%></div>
    
<% end %>
<h2>WTF</h2>

app/views/exercises/new.html.erb
<h1> Create new Exercise </h1>
<%= form_for @exercise do |f| %>
    <%= f.label :description%>
    <%= f.text_field :description%>
    <%= f.submit "Submit exercise" %>
<% end %>

app/views/exercises/show.html.erb
<h1><%= @exercise.description %></h1>
<h1><%= link_to "home", exercises_path %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExerciseTrackerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>